# 애플리케이션 설정
spring:
  application:
    name: ai-challenge-api

# OpenAI API 설정
openai:
  api:
    key: ${OPENAI_API_KEY}
    model: gpt-3.5-turbo
    max-tokens: 3000
    temperature: 0.7

# 서버 설정
server:
  port: 8080

# 로깅 설정
logging:
  level:
    JOBKOREA.AI_Challenge: DEBUG
    org.springframework.web: DEBUG
